name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  NEXT_PUBLIC_FIREBASE_API_KEY: ${{secrets.NEXT_PUBLIC_FIREBASE_API_KEY}}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install

      - name: Write functions environment variables
        run: |
          echo "OPENAI_SECRET_KEY=${{secrets.OPENAI_SECRET_KEY}}" >> apps/functions/.env
          echo "GOOGLE_OAUTH_CLIENT_SECRET=${{secrets.GOOGLE_OAUTH_CLIENT_SECRET}}" >> apps/functions/.env
          echo "AIRTABLE_OAUTH_CLIENT_SECRET=${{secrets.AIRTABLE_OAUTH_CLIENT_SECRET}}" >> apps/functions/.env

      - name: Build & Deploy
        run: npm run deploy
